# Generated by Django 5.2.8 on 2025-11-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_pdf',
        ),
    ]
